package(default_visibility = ["//visibility:private"])

cc_library(
    name = "function",
    hdrs = ["function.h"],
    srcs = ["function.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@nth_cc//nth/debug",
    ],
)
