package(default_visibility = ["//visibility:private"])

cc_library(
    name = "attributes",
    hdrs = ["attributes.h"],
    visibility = ["//jasmin:__subpackages__"],
    deps = [],
)

cc_library(
    name = "debug",
    hdrs = ["debug.h"],
    srcs = ["debug.cc"],
    visibility = ["//jasmin:__subpackages__"],
    deps = [],
)

cc_library(
    name = "function_base",
    hdrs = ["function_base.h"],
    visibility = ["//jasmin:__subpackages__"],
    deps = [
        "//jasmin:instruction_pointer",
    ],
)

cc_library(
    name = "type_traits",
    hdrs = ["type_traits.h"],
    visibility = ["//jasmin:__subpackages__"],
    deps = [],
)
