package(default_visibility = ["//visibility:private"])

cc_library(
    name = "attributes",
    hdrs = ["attributes.h"],
    # TODO: Restrict to //jasmin:__subpackages__
    visibility = ["//:__subpackages__"],
    deps = [],
)

cc_library(
    name = "type_traits",
    hdrs = ["type_traits.h"],
    # TODO: Restrict to //jasmin:__subpackages__
    visibility = ["//:__subpackages__"],
    deps = [],
)
