package(default_visibility = ["//visibility:private"])

cc_library(
    name = "compiled_function",
    hdrs = ["compiled_function.h"],
    srcs = ["compiled_function.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@nth_cc//nth/debug",
        "@nth_cc//nth/memory:bytes",
    ],
)
