name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - name: Test Debug Build
        run: >-
          bazel test -c dbg --copt=-DJASMIN_DEBUG ...
      - name: Test Hardened Build
        run: >-
          bazel test -c opt --copt=-DJASMIN_DEBUG ...
      - name: Test Optimized Build
        run: >-
          bazel test -c opt ...
